#!e:\practices\cls frs\env\scripts\python.exe
import argparse
import csv
import sys
import itertools
from six.moves import zip_longest

def readCL():
    parser = argparse.ArgumentParser()
    parser.add_argument("infile", nargs="?", type=argparse.FileType('r'), default=sys.stdin)
    args = parser.parse_args()
    return args.infile

if __name__ == "__main__":
    f_in = readCL()
    inlines = [line for line in csv.reader(f_in)]
    outlines = six.moves.zip_longest(*inlines)
    csv.writer(sys.stdout).writerows(outlines)
